package ch.heigvd.res.lab00;

import org.junit.Assert;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;

/**
 *       *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * @author Matthieu Chatelan
 */
public class BabyGrandPianoTest {

  @Test
  public void aBabyGrandPianoShoudMakeTada() {
    IInstrument BabyGrandPiano = new BabyGrandPiano();
    String sound = BabyGrandPiano.play();
    Assert.assertEquals("Tada", sound);
  }
}
