package ch.heigvd.res.lab00;

import org.junit.Assert;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;

/**
 *       *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * Magnifique test pour Bagpipe!
 * 
 * @author Basile Châtillon
 */
public class BagpipeTest {
  
  @Test
  public void BagpipeSound() {
    IInstrument bagpipe = new Bagpipe();
    String sound = bagpipe.play();
    Assert.assertEquals("tuiiitwuiututitui", sound);
  }
  
}
