package ch.heigvd.res.lab00;
import org.junit.Assert;
import org.junit.Test;

/**
 *       *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 * 
 * @author kevin moreira
 */
public class EnglishHornTest {

  @Test
  public void aEnglishHornShouldMakeFluFlu() {
    IInstrument EnglishHorn = new EnglishHorn();
    String sound = EnglishHorn.play();
    Assert.assertEquals("fluflu", sound);
  }
  }
